Repository dev-KPI/cash-flow-frontend, pull requests merged in 2023-09, with the labels that each got.

#72 [HistoryPage, ExpenseModal, StatusTooltip, ConformationModal]
  src/components/Input/Input.tsx
  src/components/Input/InputTypes.ts
  src/components/ModalWindows/ConfirtmationModal/ConfirmationModal.tsx
  src/components/ModalWindows/ExpenseModal/ExpenseModal.tsx
  src/components/StatusTooltip/StatusTooltip.tsx
  src/pages/Dashboard/UserCategoriesCard/UserCategoriesCard.tsx
  src/pages/Group/GroupCategoriesCard/GroupCategoriesCard.tsx
  src/pages/Group/GroupHeader/GroupHeader.tsx
  src/pages/GroupMembers/GroupMembers.tsx
  src/pages/History/History.module.css
  src/pages/History/History.tsx
  src/store/Controllers/ExpensesController/ExpensesController.ts
  src/store/Controllers/ExpensesController/ExpensesControllerInterfaces.ts
  src/store/Controllers/GroupsController/GroupsController.ts
  src/store/Controllers/ReplenishmentController/ReplenishmentController.ts
  src/store/Controllers/UserController/UserController.ts
Labels: enhancement

#73 [App toastify]
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/Header/MobileHeader/MenuBurger/MenuBurger.tsx
  src/components/Header/Notifications/DesktopNotifications/DesktopNotifications.tsx
  src/components/Header/Notifications/MobileNotifications/MobileNotifications.tsx
  src/components/ModalWindows/CategoryModal/CategoryModal.tsx
  src/components/ModalWindows/ConfirtmationModal/ConfirmationModal.tsx
  src/components/ModalWindows/ExpenseModal/ExpenseModal.tsx
  src/components/ModalWindows/GroupModal/GroupModal.tsx
  src/components/ModalWindows/InvitationModal/InvitationModal.tsx
  src/components/ModalWindows/OperationModal/SalaryModal.tsx
  src/components/ModalWindows/ViewMoreModal/ViewMoreModal.tsx
  src/components/StatusTooltip/StatusTooltip.module.css
  src/components/StatusTooltip/StatusTooltip.tsx
  src/pages/GroupMembers/GroupMembers.tsx
  src/pages/Groups/GroupListItem/GroupIListItem.tsx
  src/pages/Groups/GroupsPage.tsx
  src/pages/History/History.tsx
  src/store/UI_store/TooltipSlice/TooltipSlice.ts
  src/store/UI_store/TooltipSlice/TooltipSliceInterfaces.ts
  src/store/store.ts
Labels: Pending review

#71 [GroupMemberChart,. Responsive, SearchBar, UIMethod]
  src/components/Buttons/CustomButton/CustomButton.tsx
  src/components/Header/MobileHeader/MenuBurger/MenuBurger.module.css
  src/components/Header/MobileHeader/MobileHeader.tsx
  src/components/Header/Notifications/DesktopNotifications/DesktopNotifications.tsx
  src/components/Header/Notifications/MobileNotifications/MobileNotifications.module.css
  src/components/Header/Notifications/MobileNotifications/MobileNotifications.tsx
  src/components/ModalWindows/ConfirtmationModal/ConfirmationModal.tsx
  src/components/ModalWindows/ExpenseModal/ExpenseModal.tsx
  src/components/ModalWindows/GroupModal/GroupModal.module.css
  src/components/ModalWindows/GroupModal/GroupModal.tsx
  src/components/ModalWindows/OperationModal/SalaryModal.tsx
  src/components/ModalWindows/ViewMoreModal/ViewMoreModal.module.css
  src/components/ModalWindows/ViewMoreModal/ViewMoreModal.tsx
  src/components/OperationCard/OperationCard.tsx
  src/components/SearchBar/SearchBar.module.css
  src/components/SearchBar/SearchBar.tsx
  src/pages/Dashboard/UserCategoriesCard/UserCategoriesCard.module.css
  src/pages/Group/Group.module.css
  src/pages/Group/GroupHeader/GroupHeader.tsx
  src/pages/GroupMember/GroupMember.tsx
  src/pages/GroupMember/GroupMemberChartCard/GroupMemberChartCard.module.css
  src/pages/GroupMember/GroupMemberChartCard/GroupMemberChartCard.tsx
  src/pages/GroupMembers/GroupMembers.module.css
  src/pages/GroupMembers/GroupMembers.tsx
  src/pages/Groups/GroupListItem/GroupIListItem.tsx
  src/pages/Groups/GroupsPage.tsx
  src/pages/History/History.module.css
  src/pages/History/History.tsx
  src/pages/Users/Users.module.css
  src/pages/Users/Users.tsx
  src/services/DateService/DateService.ts
  src/services/UsefulMethods/UIMethods.ts
  src/store/Controllers/GroupsController/GroupsController.ts
  src/store/Controllers/GroupsController/GroupsControllerInterfaces.ts
Labels: Done

#76 [CategoryModal]
  src/components/Header/Header.tsx
  src/components/ModalWindows/CategoryModal/CategoryModal.tsx
  src/router/GroupRouter.tsx
  src/store/User/UserInterfaces.ts
  src/store/User/UserSlice.ts
Labels: Pending review

#77 [Invitations]
  src/components/Header/Notifications/DesktopNotifications/DesktopNotifications.tsx
  src/components/Header/Notifications/MobileNotifications/MobileNotifications.tsx
Labels: Pending review

#78 [Notifications, RecentActivity, GroupMembers] | Status: 👍
  src/components/Header/Notifications/MobileNotifications/MobileNotifications.module.css
  src/components/Header/Notifications/MobileNotifications/MobileNotifications.tsx
  src/components/RecentOperationsCards/RecentOperationsCards.tsx
  src/pages/Group/Group.tsx
  src/pages/Group/GroupChartsCard/GroupChartsCard.tsx
  src/pages/Group/GroupGraphCard/GroupGraphCard.tsx
  src/pages/Group/GroupHistoryCard/GroupHistoryCard.tsx
  src/pages/GroupHistory/GroupHistory.module.css
  src/pages/GroupHistory/GroupHistory.tsx
  src/pages/GroupMember/GroupMemberHistoryCard/GroupMemberHistoryCard.tsx
  src/pages/GroupMembers/GroupMembers.module.css
Labels: Pending review

#79 Fixes
  src/components/Header/PcHeader/PcHeader.tsx
  src/components/Input/Input.tsx
  src/components/ModalWindows/ExpenseModal/ExpenseModal.tsx
  src/components/ModalWindows/OperationModal/SalaryModal.tsx
  src/pages/Group/GroupSpendersCard/GroupSpendersCard.module.css
  src/pages/Group/GroupSpendersCard/GroupSpendersCard.tsx
  src/pages/GroupHistory/GroupHistory.module.css
  src/pages/GroupHistory/GroupHistory.tsx
  src/pages/GroupMember/GroupMemberHistoryCard/GroupMemberHistoryCard.tsx
Labels: Done

#81 [MenuBurger, CategoryModal, Responsive]
  src/components/Header/MobileHeader/MenuBurger/MenuBurger.module.css
  src/components/Header/MobileHeader/MenuBurger/MenuBurger.tsx
  src/components/Header/MobileHeader/MobileHeader.module.css
  src/components/Header/PcHeader/PcHeader.module.css
  src/components/Header/PcHeader/PcHeader.tsx
  src/components/ModalWindows/CategoryModal/CategoryModal.tsx
  src/pages/Dashboard/UserAccountCard/UserAccountCard.module.css
  src/pages/Dashboard/UserCategoriesCard/UserCategoriesCard.module.css
  src/pages/GroupHistory/GroupHistory.module.css
  src/pages/GroupMembers/GroupMembers.module.css
  src/pages/Users/Users.module.css
  src/pages/Users/Users.tsx
  src/router/GroupRouter.tsx
  src/store/User/UserInterfaces.ts
  src/store/User/UserSlice.ts
Labels: Done

#82 [FAQ, email privacy]
  src/components/ContextUser/ContextUser.tsx
  src/components/Header/MobileHeader/MenuBurger/MenuBurger.tsx
  src/pages/FAQ/FAQ.module.css
  src/pages/FAQ/FAQ.tsx
  src/pages/GroupMember/GroupMemberUserCard/GroupMemberUserCard.module.css
  src/pages/GroupMember/GroupMemberUserCard/GroupMemberUserCard.tsx
  src/pages/GroupMembers/GroupMembers.tsx
  src/pages/Users/Users.tsx
  src/router/routes.ts
Labels: Pending review

#83 [Charts, FAQ, RecentActivity] | Status: Fix
  src/components/Accordion/Accordion.module.css
  src/components/ChartCard/ChartCard.module.css
  src/components/ChartCard/ChartCard.tsx
  src/components/ChartCard/ChartCardDot/ChartCardDot.module.css
  src/components/ChartCard/ChartCardDot/ChartCardDot.tsx
  src/components/ChartCard/ChartCardLoader.tsx
  src/components/ContextUser/ContextUser.tsx
  src/components/Light/Light.module.css
  src/components/RecentOperationsCards/RecentOperationsCards.module.css
  src/components/RecentOperationsCards/RecentOperationsCards.tsx
  src/components/SearchBar/SearchBar.module.css
  src/pages/Dashboard/Dashboard.module.css
  src/pages/Dashboard/UserAccountCard/UserAccountCard.module.css
  src/pages/Dashboard/UserHistoryCard/UserHistoryCard.module.css
  src/pages/FAQ/FAQ.module.css
  src/pages/FAQ/FAQ.tsx
  src/pages/Group/GroupChartsCard/GroupChartsCard.module.css
  src/pages/Group/GroupChartsCard/GroupChartsCard.tsx
  src/pages/GroupHistory/GroupHistory.tsx
  src/pages/Groups/GroupListItem/GroupListItem.module.css
Labels: Pending review

#84 [GroupMemberUserCard, Graphs, GroupHeader] | Status: Fix
  src/components/GraphCard/Graph.tsx
  src/components/GraphCard/StackedGraph.tsx
  src/components/OperationCard/OperationCard.module.css
  src/components/OperationCard/OperationCard.tsx
  src/pages/Categories/CategoriesCard/CategoriesCard.module.css
  src/pages/Dashboard/UserGraphCard/UserGraphCard.tsx
  src/pages/Group/Group.module.css
  src/pages/Group/Group.tsx
  src/pages/Group/GroupGraphCard/GroupGraphCard.tsx
  src/pages/Group/GroupHeader/GroupHeader.tsx
  src/pages/GroupMember/GroupMemberUserCard/GroupMemberUserCard.module.css
  src/pages/GroupMember/GroupMemberUserCard/GroupMemberUserCard.tsx
  src/pages/GroupMember/GroupMemberUserCard/GroupMemberUserCardLoader.tsx
  src/store/UI_store/MonthPickerSlice/MonthPickerSlice.ts
Labels: Pending review

#85 [Breadcrumbs, GroupMembers, GroupHistory, History]
  src/components/Breadcrumbs/Breadcrumbs.module.css
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/pages/Expenses.ts
  src/pages/Group/GroupSpendersCard/GroupSpendersCard.module.css
  src/pages/Group/GroupSpendersCard/GroupSpendersCard.tsx
  src/pages/GroupHistory/GroupHistory.module.css
  src/pages/GroupHistory/GroupHistory.tsx
  src/pages/GroupHistoryObj.ts
  src/pages/GroupMembers/GroupMembers.module.css
  src/pages/GroupMembers/GroupMembers.tsx
  src/pages/GroupObj.ts
  src/pages/Groups/GroupListItem/GroupListItem.module.css
  src/pages/History/History.module.css
  src/pages/History/History.tsx
  src/pages/HistoryObj.ts
  src/pages/MembersHistoryObj.ts
  src/pages/MembersObj.ts
Labels: Done
